# Generated by Django 5.2.15 on 2026-07-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_devicetoken_usernotificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotificationpreference",
            name="email_comments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="email_digest_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="email_follows",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="email_likes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotificationpreference",
            name="email_messages",
            field=models.BooleanField(default=False),
        ),
    ]
