# Generated by Django 5.2.15 on 2026-07-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_usernotificationpreference_email_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("follow", "Follow"),
                    ("mention", "Mention"),
                    ("message", "Message"),
                    ("warning", "Warning"),
                ],
                max_length=20,
            ),
        ),
    ]
