# Generated by Django 5.2.15 on 2026-07-03 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
        ("stories", "0003_story_is_hidden_story_needs_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="action_taken",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_action", "No Action"),
                    ("warning_issued", "Warning Issued"),
                    ("content_removed", "Content Removed"),
                    ("user_suspended", "User Suspended"),
                    ("user_banned", "User Banned"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reported_story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received",
                to="stories.story",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("spam", "Spam"),
                    ("hate_speech", "Hate Speech"),
                    ("nudity", "Nudity"),
                    ("harassment", "Harassment"),
                    ("false_information", "False Information"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("needs_review", "Needs Review"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
