# Generated by Django 5.2.15 on 2026-07-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_count",
            field=models.IntegerField(default=0),
        ),
    ]
