# Generated by Django 5.2.15 on 2026-07-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_comment_reply_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comment",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
