# Generated by Django 5.2.15 on 2026-07-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="repost_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="repost_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reposts",
                to="posts.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("mixed", "Mixed"),
                    ("repost", "Repost"),
                    ("quote", "Quote Post"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
