# Generated by Django 5.2.15 on 2026-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
    ]
