# Generated by Django 5.2.15 on 2026-07-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_story_is_expired"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="story",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
